using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.IO;

namespace Treasurer2
{
    public partial class ProductsOfTreasurer : DevExpress.XtraEditors.XtraUserControl
    {
        private static ProductsOfTreasurer _instance;

        public static ProductsOfTreasurer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new ProductsOfTreasurer();
                return _instance;
            }
        }
        public ProductsOfTreasurer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void gridControlProduct_Load(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Load(object sender, EventArgs e)
        {
            sqlDataSource1.FillAsync();
        }


        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            if((gridView1.FocusedColumn.FieldName == "pname") ||
               (gridView1.FocusedColumn.FieldName == "ptype"))
            {
                string pid = Convert.ToString(gridView1.GetFocusedRowCellValue(colproduct_id));
                UpdatePFormDataSet(pid);
            }
            if(gridView1.FocusedColumn.FieldName == "person_responsible_for")
            {
                string username = Convert.ToString(gridView1.GetFocusedRowCellValue(colperson_responsible_for));
                UsersInfoFormDataset(username);
            }
            
        }

        public void UpdatePFormDataSet(string pid)
        {
            // songogdsn item iin medeellvvdig shine form deer gargaj irne ter ni edit bolon remove hiih bolomjtoi baih
                        
            UpdateProductForm updatePForm = new UpdateProductForm();
            PRODUCTS pRODUCTS = new PRODUCTS();
            DataTable table = pRODUCTS.getProductByID(pid);

            updatePForm.textEditID.Text = pid;
            updatePForm.textBoxProductName.Text = table.Rows[0]["pname"].ToString();
            updatePForm.comboBoxProductCategory.Text = table.Rows[0]["ptype"].ToString();
            updatePForm.dateEditManufactured.DateTime = (DateTime)table.Rows[0]["date_manufactured"];
            updatePForm.dateEditExpire.DateTime = (DateTime)table.Rows[0]["date_expire"];
            updatePForm.comboBoxOwner.Text = table.Rows[0]["person_responsible_for"].ToString();

            byte[] img = (byte[])table.Rows[0]["image"];
            MemoryStream image = new MemoryStream(img);
            updatePForm.pictureEdit.Image = Image.FromStream(image);
            updatePForm.Show(this);
                        
        }
        public void UsersInfoFormDataset(string username)
        {
            try
            {
                USERS uSERS = new USERS();
                UsersInfoForm userIForm = new UsersInfoForm();
                DataTable table = uSERS.getUserByUsername(username);

                userIForm.labelFirstname.Text = table.Rows[0]["firstname"].ToString();
                userIForm.labelLastname.Text = table.Rows[0]["lastname"].ToString();
                userIForm.labelEmailAddress.Text = table.Rows[0]["email"].ToString();
                userIForm.labelUsername.Text = username;

                byte[] img = (byte[])table.Rows[0]["picture"];
                MemoryStream image = new MemoryStream(img);
                userIForm.pictureOfUser.Image = Image.FromStream(image);

                userIForm.Show(this);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        private void toolStripButton1_Click(object sender, EventArgs e)
        {
            AddProductForm addPForm = new AddProductForm();
            addPForm.Show(this);
        }

        private void toolStripButton2_Click(object sender, EventArgs e)
        {
            if ((gridView1.FocusedColumn.FieldName == "pname") ||
               (gridView1.FocusedColumn.FieldName == "ptype"))
            {
                string pid = Convert.ToString(gridView1.GetFocusedRowCellValue(colproduct_id));
                UpdatePFormDataSet(pid);
            }
        }
    }
}
