using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.IO;

namespace Treasurer2
{
    public partial class ProductsOfTreasurer : DevExpress.XtraEditors.XtraUserControl
    {
        private static ProductsOfTreasurer _instance;


        public static ProductsOfTreasurer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new ProductsOfTreasurer();
                return _instance;
            }
        }


        MyDatabase db = new MyDatabase();
        PRODUCTS product = new PRODUCTS();


        #region ProductsOfTreasurer
        public ProductsOfTreasurer()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            MySqlCommand command = new MySqlCommand("SELECT * FROM usersdb.product;", db.getConnection());
            gridControl1.DataSource = db.getDataTable(command);


            //DateTime dateEx = gridView1.Columns.ColumnByFieldName("coldate_expire")
            //if (gridView1.Columns.ColumnByFieldName("coldate_expire") < DateTime.Now) gridView1.Columns.ColumnByFieldName("coldate_expire")
        }
        #endregion


        #region gridControl1_DoubleClick
        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            if((gridView1.FocusedColumn.FieldName == "pname") ||
               (gridView1.FocusedColumn.FieldName == "ptype"))
            {
                string pid = Convert.ToString(gridView1.GetFocusedRowCellValue(colproduct_id));

                MySqlCommand command = new MySqlCommand("CALL `usersdb`.`search_product_log_by_pid`(@PID);", db.getConnection());
                command.Parameters.Add("@PID", MySqlDbType.Int32).Value = Convert.ToInt32(pid);
                ProductLogForm productLForm = new ProductLogForm();
                productLForm.Show(this);
                productLForm.gridControlLog.DataSource = db.getDataTable(command);
                
                //UpdatePFormDataSet(pid);
            }
            if(gridView1.FocusedColumn.FieldName == "person_responsible_for")
            {
                
                string username = Convert.ToString(gridView1.GetFocusedRowCellValue(colperson_responsible_for));
                UsersInfoFormDataset(username);
                
                
            }
            
        }
        #endregion


        #region UpdatePFormDataSet
        public void UpdatePFormDataSet(string pid)
        {
            // songogdsn item iin medeellvvdig shine form deer gargaj irne ter ni edit bolon remove hiih bolomjtoi baih

            UpdateProductForm updatePForm = new UpdateProductForm();
            try
            {
                MySqlCommand command = new MySqlCommand("CALL `usersdb`.`select_product_by_id`(" + pid + ")", db.getConnection());
                DataTable table = db.getDataTable(command);


                updatePForm.textEditID.Text = pid;
                updatePForm.textBoxProductName.Text = table.Rows[0]["pname"].ToString();
                updatePForm.glueCategory.Text = table.Rows[0]["ptype"].ToString();
                updatePForm.dateEditManufactured.DateTime = (DateTime)table.Rows[0]["date_manufactured"];
                updatePForm.dateEditExpire.DateTime = (DateTime)table.Rows[0]["date_expire"];
                updatePForm.glueOwner.Text = table.Rows[0]["person_responsible_for"].ToString();

                updatePForm.textEditQuantity.Text = table.Rows[0]["stock_quantity"].ToString();
                updatePForm.textEditPrice.Text = table.Rows[0]["price"].ToString();

                byte[] img = (byte[])table.Rows[0]["image"];
                MemoryStream image = new MemoryStream(img);
                updatePForm.pictureEdit.Image = Image.FromStream(image);

                updatePForm.Show();
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        #endregion


        #region UsersInfoFormDataset
        public void UsersInfoFormDataset(string username)
        {
            try
            {
                UsersInfoForm userIForm = new UsersInfoForm();

                MySqlCommand command = new MySqlCommand("CALL `usersdb`.`select_user_by_username`(@username);", db.getConnection());
                command.Parameters.Add("@username", MySqlDbType.VarChar).Value = username;
                DataTable table = db.getDataTable(command);

                userIForm.labelFirstname.Text = table.Rows[0]["firstname"].ToString();
                userIForm.labelLastname.Text = table.Rows[0]["lastname"].ToString();
                userIForm.labelEmailAddress.Text = table.Rows[0]["email"].ToString();
                userIForm.labelUsername.Text = username;

                byte[] img = (byte[])table.Rows[0]["picture"];
                MemoryStream image = new MemoryStream(img);
                userIForm.pictureOfUser.Image = Image.FromStream(image);

                userIForm.Show(this);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        #endregion


        #region toolStripButtonDelete_Click
        private void toolStripButtonDelete_Click(object sender, EventArgs e)
        {
            PRODUCTS product = new PRODUCTS();
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue(colproduct_id));

            if (MessageBox.Show("Та " + id + " бүртгэлийн дугаартай эд хөрөнгийг бүртгэлээс устгахдаа итгэлтэй байна уу?", "Устгах", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                product.deleteProduct(id);
                
                MessageBox.Show("Эд хөрөнгө бүртгэлээс устлаа", "Устгах", MessageBoxButtons.OK, MessageBoxIcon.Information);

                MySqlCommand command = new MySqlCommand("SELECT * FROM usersdb.product;", db.getConnection());
                refreshGridview(command);
            }
            else
            {
                MessageBox.Show("Эд хөрөнгө бүртгэлээс устсангүй", "Устгах", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

        }
        #endregion


        #region toolStripButtonAdd_Click
        private void toolStripButtonAdd_Click(object sender, EventArgs e)
        {
            AddProductForm addPForm = new AddProductForm();
            addPForm.Show(this);
        }
        #endregion


        #region   ButtonEditEvent
        private void toolStripButtonEdit_Click(object sender, EventArgs e)
        {
            if (gridView1.GetFocusedRowCellValue(colproduct_id) != null)
            {
                string pid = Convert.ToString(gridView1.GetFocusedRowCellValue(colproduct_id));
                UpdatePFormDataSet(pid);
            }
        }
        #endregion


        #region toolStripButtonRefresh_Click
        private void toolStripButtonRefresh_Click(object sender, EventArgs e)
        {
            toolStripTextBoxSearch.Text = "";
            MySqlCommand command = new MySqlCommand("SELECT * FROM usersdb.product;", db.getConnection());
            refreshGridview(command);

        }
        #endregion


        #region refreshGridview
        public void refreshGridview(MySqlCommand command)
        {
            DataTable table = db.getDataTable(command);
            gridControl1.DataSource = table;
        }
        #endregion


        #region toolStripSearchButton_Click
        private void toolStripButton1_Click(object sender, EventArgs e)
        {
            if(toolStripTextBoxSearch.Text != "")
            {
                string searchInput = toolStripTextBoxSearch.Text;

                MySqlCommand command = new MySqlCommand("CALL `usersdb`.`search_product_by_id_pn_pt_prf`('%" + searchInput + "%');", db.getConnection());

                DataTable table = db.getDataTable(command);
                
                if (table.Rows.Count > 0)
                {
                    gridControl1.DataSource = table;

                    db.closeConnection();
                }
                else
                {
                    MessageBox.Show("'" + searchInput + "' утгатай хайлтын илэрц олдсонгүй", "Олдсонгүй", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    db.closeConnection();
                }
                
            }
        }
        #endregion


        #region toolStripPrintButton_Click
        private void toolStripButton1_Click_1(object sender, EventArgs e)
        {
            XtraReport1 xtraReport1 = new XtraReport1();
            try
            {
                
                if (gridView1.GetFocusedRowCellValue(colproduct_id) != null)
                {
                    MySqlCommand command = new MySqlCommand("SELECT `pname`,`ptype`,`stock_quantity`,`price` FROM `usersdb`.`product`WHERE product_id = @pid;", db.getConnection());
                    command.Parameters.Add("@pid", MySqlDbType.Int32).Value = Convert.ToInt32(gridView1.GetFocusedRowCellValue(colproduct_id));
                    DataTable productTable = db.getDataTable(command);

                    //MySqlDataAdapter adapter = new MySqlDataAdapter(command);


                    if (MessageBox.Show("Та энэ эд хөрөнгийн талаар хэвлэмэээр байна уу", "Хэвлэх", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        //product info table
                        xtraReport1.xrTableCellPID.Text = gridView1.GetFocusedRowCellValue(colproduct_id).ToString();
                        xtraReport1.xrTableCellPName.Text = productTable.Rows[0]["pname"].ToString();
                        xtraReport1.xrTableCellPType.Text = productTable.Rows[0]["ptype"].ToString();
                        xtraReport1.xrTableCellQuantity.Text = productTable.Rows[0]["stock_quantity"].ToString();
                        xtraReport1.xrTableCellPrice.Text = productTable.Rows[0]["price"].ToString();
                        
                        // log table iin 
                        //xtraReport1.xrTableCellLogID.bin = productTable.Columns["price"];
                        xtraReport1.Print();
                    }
                    else
                    {
                        MessageBox.Show("Хэвлэсэнүй", "Хэвлэх", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        public void printProductOwning(string productName, string productCategory)
        {

        }

        private void addLogToolStripMenuItem_Click(object sender, EventArgs e)
        {
            ProductLogForm productLForm = new ProductLogForm();
            productLForm.Show(this);
        }

    }
}
