using DevExpress.XtraEditors;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Treasurer2
{
    public partial class UsersOfTreasurer : DevExpress.XtraEditors.XtraUserControl
    {
        private static UsersOfTreasurer _instance;

        public static UsersOfTreasurer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new UsersOfTreasurer();
                return _instance;
            }
        }

        MyDatabase db = new MyDatabase();
        public UsersOfTreasurer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            //sqlDataSource2.FillAsync();
            MySqlCommand command = new MySqlCommand("SELECT * FROM usersdb.users_of_treasurer;", db.getConnection());
            DataTable table = fillDataGrid(command);
            gridControlUsers.DataSource = table;
        }

        private void toolStripButtonAdd_Click(object sender, EventArgs e)
        {
            AddUserForm addUForm = new AddUserForm();
            addUForm.Show(this);
        }

        private void toolStripButtonEdit_Click(object sender, EventArgs e)
        {

        }

        private void toolStripButtonDelete_Click(object sender, EventArgs e)
        {

        }

        private void toolStripButtonRefresh_Click(object sender, EventArgs e)
        {
            UsersOfTreasurer usersOfTreasurer = new UsersOfTreasurer();
            toolStripTextBoxSearch.Text = "";
            usersOfTreasurer.InitializeComponent();
            MySqlCommand command = new MySqlCommand("SELECT * FROM usersdb.users_of_treasurer;", db.getConnection());

            DataTable table = fillDataGrid(command);
            gridControlUsers.DataSource = table;
        }

        private void toolStripButtonSearch_Click(object sender, EventArgs e)
        {

        }
        public DataTable fillDataGrid(MySqlCommand command)
        {
            MySqlDataAdapter adapter = new MySqlDataAdapter(command);
            DataTable table = new DataTable();
            adapter.Fill(table);
            return table;
        }
    }
}
